import type { Hero } from "../src/utils/types";


export const heroesList: Hero[] = [
    {
        name: "D.Va",
        age: "19 years",
        nationality: "Korean",
        role: "Tank",
        health: 650,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/1a/OW2_Dva.png/revision/latest/scale-to-width-down/345?cb=20220930190845",
    },
    {
        name: "Doomfist",
        age: "45 years",
        nationality: "Nigerian",
        role: "Tank",
        health: 450,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/15/Doomfist_Artwork.png/revision/latest/scale-to-width-down/252?cb=20170927195416",
    }, {
        name: "Junker Queen",
        age: "37 years",
        nationality: "Australian",
        role: "Tank",
        health: 425,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/b/be/Junker_Queen-portrait.png/revision/latest/scale-to-width-down/140?cb=20221114212951",
    }, {
        name: "Orisa",
        age: "1 month",
        nationality: "Numbanian",
        role: "Tank",
        health: 550,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/d4/Orisa_Skin_Overwatch_2.png/revision/latest/scale-to-width-down/309?cb=20221116224621",
    }, {
        name: "Ramattra",
        age: "25 years",
        nationality: "Omnic",
        role: "Tank",
        health: 450,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/71/Ramattra-portrait.png/revision/latest/scale-to-width-down/266?cb=20221114213307",
    }, {
        name: "Reinhardt",
        age: "61 years",
        nationality: "German",
        role: "Tank",
        health: 625,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/3b/Reinhardt-ow2-portrait.png/revision/latest/scale-to-width-down/252?cb=20191104214011",
    }, {
        name: "Roadhog",
        age: "48 years",
        nationality: "Australian",
        role: "Tank",
        health: 700,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/ce/Roadhog-Portrait.png/revision/latest/scale-to-width-down/345?cb=20160620014755",
    }, {
        name: "Sigma",
        age: "62 years",
        nationality: "Dutch",
        role: "Tank",
        health: 350,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/80/Sigma.png/revision/latest/scale-to-width-down/259?cb=20190724005755",
    }, {
        name: "Winston",
        age: "29 years",
        nationality: "Animal",
        role: "Tank",
        health: 550,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/7c/Winston-ow2-portrait.png/revision/latest/scale-to-width-down/279?cb=20191104221341",
    }, {
        name: "Ashe",
        age: "39 years",
        nationality: "American",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/4/4f/Ashe-portrait.png/revision/latest/scale-to-width-down/330?cb=20190227082739",
    }, {
        name: "Bastion",
        age: "30 years",
        nationality: "Robot",
        role: "Damage",
        health: 300,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/4/47/OW2-Bastion.png/revision/latest/scale-to-width-down/272?cb=20220409014728",
    }, {
        name: "Cassidy",
        age: "37 years",
        nationality: "American",
        role: "Damage",
        health: 225,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/2e/OW2_McCree.png/revision/latest/scale-to-width-down/272?cb=20210623082527",
    }, {
        name: "Echo",
        age: "Unknown",
        nationality: "Robot",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/b/bf/Echo-portrait.png/revision/latest/scale-to-width-down/166?cb=20200319191504",
    }, {
        name: "Genji",
        age: "35 years",
        nationality: "Japanese",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/6/6d/Genji-ow2-portrait.png/revision/latest/scale-to-width-down/149?cb=20191104043734",
    }, {
        name: "Hanzo",
        age: "38 years",
        nationality: "Japanese",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/6/66/OW2_Hanzo.png/revision/latest/scale-to-width-down/146?cb=20221029021242",
    }, {
        name: "Junkrat",
        age: "25 years",
        nationality: "Australian",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/9/99/Junkrat-Portrait.png/revision/latest/scale-to-width-down/286?cb=20160620014456",
    }, {
        name: "Mei",
        age: "31 years",
        nationality: "Chinese",
        role: "Damage",
        health: 250,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/da/Mei-ow2-portrait.png/revision/latest/scale-to-width-down/165?cb=20191104081317",
    }, {
        name: "Pharah",
        age: "32 years",
        nationality: "Egyptian",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/b/b3/OW2_Pharah.png/revision/latest/scale-to-width-down/272?cb=20210623082353",
    }, {
        name: "Soldier: 76",
        age: "50 years",
        nationality: "American",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/75/S76_Skin_Overwatch_2.png/revision/latest/scale-to-width-down/197?cb=20221009113643",
    }, {
        name: "Sojourn",
        age: "53 years",
        nationality: "Canadian",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/32/Sojourn-portrait.png/revision/latest/scale-to-width-down/245?cb=20221114212840",
    }, {
        name: "Sombra",
        age: "30 years",
        nationality: "Mexican",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/d7/OW2_Sombra.png/revision/latest/scale-to-width-down/272?cb=20210623082827",
    }, {
        name: "Symmetra",
        age: "28 years",
        nationality: "Indian",
        role: "Damage",
        health: 225,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/18/Symmetra-portrait.png/revision/latest/scale-to-width-down/161?cb=20160620015059",
    }, {
        name: "Torbjörn",
        age: "57 years",
        nationality: "Swedish",
        role: "Damage",
        health: 250,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/db/Torbj%C3%B6rn-ow2-portrait.png/revision/latest/scale-to-width-down/272?cb=20210623082654",
    }, {
        name: "Tracer",
        age: "26 years",
        nationality: "British",
        role: "Damage",
        health: 150,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/1b/Tracer_ow2_portrait.png/revision/latest/scale-to-width-down/116?cb=20220625025656",
    }, {
        name: "Widowmaker",
        age: "33 years",
        nationality: "French",
        role: "Damage",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/ab/OW2_Widowmaker.png/revision/latest/scale-to-width-down/272?cb=20210623082021",
    }, {
        name: "Ana",
        age: "60 years",
        nationality: "Egyptian",
        role: "Support",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/76/Ana.png/revision/latest/scale-to-width-down/143?cb=20160715094551",
    }, {
        name: "Baptiste",
        age: "36 years",
        nationality: "Haitian",
        role: "Support",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/00/OW2_Baptiste.png/revision/latest/scale-to-width-down/272?cb=20210623082803",
    }, {
        name: "Brigitte",
        age: "23 years",
        nationality: "Swedish",
        role: "Support",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/83/OW2_Brigitte.png/revision/latest/scale-to-width-down/168?cb=20220930191642",
    }, {
        name: "Kiriko",
        age: "20 years",
        nationality: "Japanese",
        role: "Support",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/d4/Kiriko-portrait.png/revision/latest/scale-to-width-down/293?cb=20221114213127",
    }, {
        name: "Lúcio",
        age: "26 years",
        nationality: "Brazilian",
        role: "Support",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/c1/Lucio-ow2-portrait.png/revision/latest/scale-to-width-down/148?cb=20191104073705",
    }, {
        name: "Mercy",
        age: "37 years",
        nationality: "Swiss",
        role: "Support",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/0f/Mercy-ow2-portrait.png/revision/latest/scale-to-width-down/149?cb=20191104213936",
    }, {
        name: "Moira",
        age: "48 years",
        nationality: "Irish",
        role: "Support",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/b/b5/Moira.png/revision/latest/scale-to-width-down/162?cb=20171104021652",
    }, {
        name: "Zenyatta",
        age: "20 years",
        nationality: "Omnic",
        role: "Support",
        health: 200,
        image: "https://static.wikia.nocookie.net/overwatch_gamepedia/images/9/92/Zenyatta-portrait.png/revision/latest/scale-to-width-down/269?cb=20160620015935",
    }
]  