import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { trpc } from "../utils/trpc";
import type { Hero } from "../utils/types";
const Home: NextPage = () => {

  //const [currentHero, setCurrentHero] = useState<Hero>()
  const [heroes, setHeroes] = useState<Hero[]>()
  const { isLoading, data } = trpc.heroes.getAll.useQuery()

  useEffect(() => {
    if (!isLoading) {
      const tmp = JSON.parse(JSON.stringify(data))
      setHeroes(tmp)
    }
  }, [setHeroes, data, isLoading])

  console.log(heroes)

  return (

    <>
      <Head>
        <title>Overwatchdle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-mainbg bg-cover bg-no-repeat">

        <p className="text-8xl justify-self-start mt-7">Overwatchdle</p>
        <div className="my-12" />
        <div className="flex flex-col gap-2 mt-2">

          <Link href="/agehol"><button className="text-6xl bg-blue text-white p-4 rounded-lg" >Higher or Lower</button></Link>
          {/** 
          <button className="border-2 border-black text-sm">Game mode 2</button>
          <button className="border-2 border-black text-sm">Game mode 3</button>
          <button className="border-2 border-black text-sm">Game mode 4</button>
         */}
        </div>
      </main>
    </>
  );
};

export default Home;
