import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ClassRegistry } from "superjson/dist/class-registry";
import type { Hero } from "../utils/types";
const Home: NextPage = () => {
  
  //const [currentHero, setCurrentHero] = useState<Hero>()

  
  return (
    
    <>
      <Head>
        <title>Overwatchdle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-mainbg bg-cover bg-no-repeat">
        
        <p className="text-8xl justify-self-start my-11">Overwatchdle</p>
        <div className="flex flex-col gap-2 mt-4">
         
          <Link href={{pathname:"/agehol"}}><button className="text-4xl bg-[#218ffe] text-white p-6 rounded-sm">Game mode 1</button></Link>
          {/** 
          <button className="border-2 border-black text-sm">Game mode 2</button>
          <button className="border-2 border-black text-sm">Game mode 3</button>
          <button className="border-2 border-black text-sm">Game mode 4</button>
         */}
        </div>
      </main>
    </>
  );
};

export default Home;
